<?php

Router::connect('/', array('controller' => 'pages', 'action' => 'index'));
Router::connect('/profile/*', array('controller' => 'profiles', 'action' => 'index'));
Router::connect('/index.html', array('controller' => 'pages', 'action' => 'index'));
Router::connect('/programs_data.html', array('controller' => 'pages', 'action' => 'programs_data'));
Router::connect('/sign_up.html', array('controller' => 'pages', 'action' => 'sign_up'));
Router::connect('/academic_goals.html', array('controller' => 'pages', 'action' => 'academic_goals'));
Router::connect('/career.html', array('controller' => 'pages', 'action' => 'career'));
Router::connect('/about.html', array('controller' => 'pages', 'action' => 'about'));
Router::connect('/contact.html', array('controller' => 'pages', 'action' => 'contact'));
Router::connect('/paypal_cancel.html', array('controller' => 'pages', 'action' => 'paypal_cancel'));
Router::connect('/paypal_sucess.html', array('controller' => 'pages', 'action' => 'paypal_sucess'));
Router::connect('/renew.html', array('controller' => 'pages', 'action' => 'renew'));
Router::connect('/my_career.html', array('controller' => 'pages', 'action' => 'my_career'));
Router::connect('/school_registration.html', array('controller' => 'pages', 'action' => 'school_registration'));
Router::connect('/career_conection.html', array('controller' => 'pages', 'action' => 'career_conection'));

Router::connect('/tracker.html', array('controller' => 'dashboards', 'action' => 'tracker'));
Router::connect('/individual_dashboard.html', array('controller' => 'dashboards', 'action' => 'index'));
Router::connect('/certify.html', array('controller' => 'dashboards', 'action' => 'certify'));
Router::connect('/icons.html', array('controller' => 'dashboards', 'action' => 'icons'));
Router::connect('/typography.html', array('controller' => 'dashboards', 'action' => 'typography'));
Router::connect('/user.html', array('controller' => 'dashboards', 'action' => 'user'));
Router::connect('/reciept.html', array('controller' => 'dashboards', 'action' => 'reciept'));
Router::connect('/view.html', array('controller' => 'dashboards', 'action' => 'view'));
Router::connect('/work_references.html', array('controller' => 'dashboards', 'action' => 'work_references'));
Router::connect('/process.html', array('controller' => 'dashboards', 'action' => 'process'));
Router::connect('/complete.html', array('controller' => 'dashboards', 'action' => 'complete'));
Router::connect('/new_value.html', array('controller' => 'dashboards', 'action' => 'new_value'));
Router::connect('/process_view.html', array('controller' => 'dashboards', 'action' => 'process_view'));
Router::connect('/complete_view.html', array('controller' => 'dashboards', 'action' => 'complete_view'));
Router::connect('/new_view.html', array('controller' => 'dashboards', 'action' => 'new_view'));
Router::connect('/transfer.html', array('controller' => 'dashboards', 'action' => 'transfer'));
Router::connect('/legal_docs.html', array('controller' => 'dashboards', 'action' => 'legal_docs'));
Router::connect('/decline.html', array('controller' => 'dashboards', 'action' => 'decline'));
Router::connect('/industry_signup.html', array('controller' => 'dashboards', 'action' => 'industry_signup'));
Router::connect('/paypal_cancel_val.html', array('controller' => 'dashboards', 'action' => 'paypal_cancel_val'));
Router::connect('/paypal_sucess_val.html', array('controller' => 'dashboards', 'action' => 'paypal_sucess_val'));
Router::connect('/payment_history.html', array('controller' => 'dashboards', 'action' => 'payment_history'));
Router::connect('/cd_player.html', array('controller' => 'dashboards', 'action' => 'cd_player'));
Router::connect('/my_cd.html', array('controller' => 'dashboards', 'action' => 'my_cd'));
Router::connect('/my_cd_data.html', array('controller' => 'dashboards', 'action' => 'my_cd_data'));
Router::connect('/terms_conditions.html', array('controller' => 'dashboards', 'action' => 'terms_conditions'));
Router::connect('/legal_docs_print.html', array('controller' => 'dashboards', 'action' => 'legal_docs_print'));
Router::connect('/referal_list.html', array('controller' => 'dashboards', 'action' => 'referal_list'));
Router::connect('/career_connection.html', array('controller' => 'dashboards', 'action' => 'career_connection'));
Router::connect('/job_alert.html', array('controller' => 'dashboards', 'action' => 'job_alert'));
Router::connect('/coop_alert.html', array('controller' => 'dashboards', 'action' => 'coop_alert'));
Router::connect('/intern_alert.html', array('controller' => 'dashboards', 'action' => 'intern_alert'));
Router::connect('/job_detail.html', array('controller' => 'dashboards', 'action' => 'job_detail'));
Router::connect('/education.html', array('controller' => 'dashboards', 'action' => 'education'));
Router::connect('/my_job.html', array('controller' => 'dashboards', 'action' => 'my_job'));
Router::connect('/job_fair.html', array('controller' => 'dashboards', 'action' => 'job_fair'));
Router::connect('/online_interview.html', array('controller' => 'dashboards', 'action' => 'online_interview'));
Router::connect('/webinars.html', array('controller' => 'dashboards', 'action' => 'webinars'));
Router::connect('/work_experience.html', array('controller' => 'dashboards', 'action' => 'work_experience'));

Router::connect('/admin_index.html', array('controller' => 'admins', 'action' => 'admin_index'));
Router::connect('/admin_dashboard.html', array('controller' => 'admins', 'action' => 'index'));
Router::connect('/invited.html', array('controller' => 'admins', 'action' => 'invited'));
Router::connect('/canada_student_trail.html', array('controller' => 'admins', 'action' => 'canada_student_trail'));
Router::connect('/new_page.html', array('controller' => 'admins', 'action' => 'new_page'));
Router::connect('/new_profile.html', array('controller' => 'admins', 'action' => 'new_profile'));
Router::connect('/payment.html', array('controller' => 'admins', 'action' => 'payment'));
Router::connect('/lookup.html', array('controller' => 'admins', 'action' => 'lookup'));
Router::connect('/transfer_payment.html', array('controller' => 'admins', 'action' => 'transfer_payment'));
Router::connect('/corporate.html', array('controller' => 'admins', 'action' => 'corporate'));
Router::connect('/canada_career_starter.html', array('controller' => 'admins', 'action' => 'canada_career_starter'));
Router::connect('/canada_career_advanced.html', array('controller' => 'admins', 'action' => 'canada_career_advanced'));
Router::connect('/canada_access360.html', array('controller' => 'admins', 'action' => 'canada_access360'));
Router::connect('/canada_unemployed_trail.html', array('controller' => 'admins', 'action' => 'canada_unemployed_trail'));
Router::connect('/canada_unemployed_career_starter.html', array('controller' => 'admins', 'action' => 'canada_unemployed_career_starter'));
Router::connect('/canada_unemployed_career_advanced.html', array('controller' => 'admins', 'action' => 'canada_unemployed_career_advanced'));
Router::connect('/canada_unemployed_career_access360.html', array('controller' => 'admins', 'action' => 'canada_unemployed_career_access360'));
Router::connect('/canada_careeradvance_trail.html', array('controller' => 'admins', 'action' => 'canada_careeradvance_trail'));
Router::connect('/canada_alumni_career_starter.html', array('controller' => 'admins', 'action' => 'canada_alumni_career_starter'));
Router::connect('/canada_alumni_career_advance.html', array('controller' => 'admins', 'action' => 'canada_alumni_career_advance'));
Router::connect('/canada_alumni_acess360.html', array('controller' => 'admins', 'action' => 'canada_alumni_acess360'));
Router::connect('/america_student_trail.html', array('controller' => 'admins', 'action' => 'america_student_trail'));
Router::connect('/america_student_career_starter.html', array('controller' => 'admins', 'action' => 'america_student_career_starter'));
Router::connect('/america_student_career_advanced.html', array('controller' => 'admins', 'action' => 'america_student_career_advanced'));
Router::connect('/america_student_access360.html', array('controller' => 'admins', 'action' => 'america_student_access360'));
Router::connect('/america_unemployed_trail.html', array('controller' => 'admins', 'action' => 'america_unemployed_trail'));
Router::connect('/america_unemployed_career_starter.html', array('controller' => 'admins', 'action' => 'america_unemployed_career_starter'));
Router::connect('/america_unemployed_career_advance.html', array('controller' => 'admins', 'action' => 'america_unemployed_career_advance'));
Router::connect('/america_unemployed_access360.html', array('controller' => 'admins', 'action' => 'america_unemployed_access360'));
Router::connect('/america_career_advance_trail.html', array('controller' => 'admins', 'action' => 'america_career_advance_trail'));
Router::connect('/america_alumni_career_starter.html', array('controller' => 'admins', 'action' => 'america_alumni_career_starter'));
Router::connect('/america_alumni_career_advance.html', array('controller' => 'admins', 'action' => 'america_alumni_career_advance'));
Router::connect('/america_alumni_access360.html', array('controller' => 'admins', 'action' => 'america_alumni_access360'));
Router::connect('/school_register.html', array('controller' => 'admins', 'action' => 'school_register'));
Router::connect('/registered_school.html', array('controller' => 'admins', 'action' => 'registered_school'));
Router::connect('/seo_data.html', array('controller' => 'admins', 'action' => 'seo_data'));
Router::connect('/add_tax.html', array('controller' => 'admins', 'action' => 'add_tax'));
Router::connect('/view_tax.html', array('controller' => 'admins', 'action' => 'view_tax'));
Router::connect('/school_payment.html', array('controller' => 'admins', 'action' => 'school_payment'));
Router::connect('/ambasdor_prgrm.html', array('controller' => 'admins', 'action' => 'ambasdor_prgrm'));
Router::connect('/user_referal_list.html', array('controller' => 'admins', 'action' => 'user_referal_list'));

Router::connect('/industry_index.html', array('controller' => 'industrys', 'action' => 'industry_index'));
Router::connect('/new_reference.html', array('controller' => 'industrys', 'action' => 'index'));
Router::connect('/archived.html', array('controller' => 'industrys', 'action' => 'archived'));
Router::connect('/Standard.html', array('controller' => 'industrys', 'action' => 'Standard'));
Router::connect('/Advance.html', array('controller' => 'industrys', 'action' => 'Advance'));
Router::connect('/confirm_verify.html', array('controller' => 'industrys', 'action' => 'confirm_verify'));
Router::connect('/co_op.html', array('controller' => 'industrys', 'action' => 'co_op'));

Router::connect('/choose_program.html', array('controller' => 'schools', 'action' => 'index'));
Router::connect('/account_admin.html', array('controller' => 'schools', 'action' => 'account_admin'));
Router::connect('/billing_info.html', array('controller' => 'schools', 'action' => 'billing_info'));
Router::connect('/embed_code.html', array('controller' => 'schools', 'action' => 'embed_code'));
Router::connect('/school_dashboard.html', array('controller' => 'schools', 'action' => 'school_dashboard'));
Router::connect('/upload_logo.html', array('controller' => 'schools', 'action' => 'upload_logo'));
Router::connect('/school.html', array('controller' => 'schools', 'action' => 'school'));
Router::connect('/school_signup.html', array('controller' => 'schools', 'action' => 'school_signup'));
Router::connect('/student_payment.html', array('controller' => 'schools', 'action' => 'student_payment'));
Router::connect('/school_paypal_success.html', array('controller' => 'schools', 'action' => 'school_paypal_success'));
Router::connect('/school_paypal_cancel.html', array('controller' => 'schools', 'action' => 'school_paypal_cancel'));
Router::connect('/school_paypal_cancel.html', array('controller' => 'schools', 'action' => 'school_paypal_cancel'));


Router::connect('/recruiter_dashboard.html', array('controller' => 'recruiters', 'action' => 'index'));
Router::connect('/job_tracking.html', array('controller' => 'recruiters', 'action' => 'job_tracking'));
Router::connect('/job_post.html', array('controller' => 'recruiters', 'action' => 'job_post'));
Router::connect('/candidate_detail.html', array('controller' => 'recruiters', 'action' => 'candidate_detail'));
Router::connect('/company_bill.html', array('controller' => 'recruiters', 'action' => 'company_bill'));
Router::connect('/view_job.html', array('controller' => 'recruiters', 'action' => 'view_job'));
Router::connect('/co_op_form.html', array('controller' => 'recruiters', 'action' => 'co_op_form'));
Router::connect('/intern_form.html', array('controller' => 'recruiters', 'action' => 'intern_form'));



CakePlugin::routes();
require CAKE . 'Config' . DS . 'routes.php';
